### ISSUE TITLE
Error trying to use PyVISA-py on Windows

### ISSUE THREAD

**Issue by jonnojohnson** [hgrecco/pyvisa-py#5]
I've been using the Agilent (now Keysight) VISA implementation with PyVISA for some time on my Windows machine.
I just tried installing PyVISA-py using:
```
pip install -U https://github.com/hgrecco/pyvisa-py/zipball/master
```
However I get:
```
Python 2.7.7 |Anaconda 2.0.1 (32-bit)| (default, Jun 11 2014, 10:41:43) [MSC v.1
500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import visa
>>> rm = visa.ResourceManager('@py')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda\lib\site-packages\pyvisa\highlevel.py", line 1471, in __new_
_
    visa_library = open_visa_library(visa_library)
  File "C:\Anaconda\lib\site-packages\pyvisa\highlevel.py", line 1440, in open_v
isa_library
    cls = get_wrapper_class(wrapper)
  File "C:\Anaconda\lib\site-packages\pyvisa\highlevel.py", line 1420, in get_wr
apper_class
    pkg = __import__(pkgname)
  File "C:\Anaconda\lib\site-packages\pyvisa-py\__init__.py", line 26, in <modul
e>
    from .highlevel import PyVisaLibrary
  File "C:\Anaconda\lib\site-packages\pyvisa-py\highlevel.py", line 20, in <modu
le>
    from pyvisa.compat import integer_types, OrderedDict
ImportError: cannot import name OrderedDict
```
This is the debug info output:
```
C:\Users\marnj>python -c "from pyvisa import util; util.get_debug_info()"
Machine Details:
   Platform ID:    Windows-7-6.1.7601-SP1
   Processor:      Intel64 Family 6 Model 58 Stepping 9, GenuineIntel

Python:
   Implementation: CPython
   Executable:     C:\Anaconda\python.exe
   Version:        2.7.7
   Compiler:       MSC v.1500 32 bit (Intel)
   Bits:           32bit
   Build:          Jun 11 2014 10:41:43 (#default)
   Unicode:        UCS2

VISA:
   PyVISA Version: 1.6.1.dev0

   #1: C:\windows\system32\visa32.dll
      found by: auto
      bitness: 32
   #2: C:\windows\system32\visa32.dll
      found by: auto
      bitness: 32
```

**Comment by hgrecco** [comment]
I am closing this for now. Feel free to reopen if necessary.

**Comment by jonnojohnson** [comment]
This should perhaps be a separate issue but I'm now getting this as my debug info:
```

C:\Anaconda>python -m visa info
Machine Details:
   Platform ID:    Windows-7-6.1.7601-SP1
   Processor:      Intel64 Family 6 Model 58 Stepping 9, GenuineIntel

Python:
   Implementation: CPython
   Executable:     C:\Anaconda\python.exe
   Version:        2.7.7
   Compiler:       MSC v.1500 32 bit (Intel)
   Bits:           32bit
   Build:          Jun 11 2014 10:41:43 (#default)
   Unicode:        UCS2

PyVISA Version: 1.6.3.dev0

Backends:
   ni:
      Version: 1.6.3.dev0 (bundled with PyVISA)
      #1: C:\windows\system32\visa32.dll:
         found by: auto
         bitness: 32
         Vendor: Keysight Technologies
         Impl. Version: 1359258704
         Spec. Version: 5243136
      #2: C:\windows\system32\visa32.dll:
         found by: auto
         bitness: 32
         Vendor: Keysight Technologies
         Impl. Version: 1359258704
         Spec. Version: 5243136
   py:
      Could not obtain debug info
      -> global name 'serial' is not defined
```
I just updated both PyVISA & PyVISA-py from the master on github about an hour ago. I don't have PySerial installed.

Also:
- Why does the VISA32.dll show up twice?
- Would it be possible to change the name of the first backend category from "ni" to that pulled from the Vendor? Or perhaps change it to "Proprietary" or something.
