### ISSUE TITLE
Error with Serial communication `serial.py`

### ISSUE THREAD

**Issue by bkprecision** [hgrecco/pyvisa-py#8]
Getting an error when trying to connect to a device using cp210x driver. Here's the output of the error. My best guess is it has something to do with `/dev/ttyAMC0` existing while `/DEV/TTYAMC0` definitely does not exist.

    Python 2.7.8 (default, Oct 30 2014, 18:30:15)
    [GCC 4.9.1] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import visa
    >>> rm = visa.ResourceManager("@py")
    >>> rm.list_resources()
    (u'ASRL/dev/ttyACM0::INSTR',)
    >>> inst = rm.open_resource("ASRL/dev/ttyACM0::INSTR")
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/PyVISA-1.6.2.dev0-py2.7.egg/pyvisa/highlevel.py", line 1631, in open_resource
        res.open(access_mode, open_timeout)
      File "/usr/local/lib/python2.7/dist-packages/PyVISA-1.6.2.dev0-py2.7.egg/pyvisa/resources/resource.py", line 165, in open
        self.session, status = self._resource_manager.open_bare_resource(self._resource_name, access_mode, open_timeout)
      File "/usr/local/lib/python2.7/dist-packages/PyVISA-1.6.2.dev0-py2.7.egg/pyvisa/highlevel.py", line 1595, in open_bare_resource
        return self.visalib.open(self.session, resource_name, access_mode, open_timeout)
      File "pyvisa-py/highlevel.py", line 180, in open
        sess = cls(session, resource_name, parsed)
      File "pyvisa-py/sessions.py", line 156, in __init__
        self.after_parsing()
      File "pyvisa-py/serial.py", line 61, in after_parsing
        self.interface = serial.Serial(port=self.parsed['board'], timeout=2000, writeTimeout=2000)
      File "/usr/local/lib/python2.7/dist-packages/serial/serialutil.py", line 261, in __init__
        self.open()
      File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 358, in open
        raise SerialException("could not open port %s,%s: %s" % (self._port, self.portstr, msg))
    serial.serialutil.SerialException: could not open port /DEV/TTYACM0,/DEV/TTYACM0: [Errno 2] No such file or directory: '/DEV/TTYACM0'

**Comment by hgrecco** [comment]
Is the master branch working for you?

**Comment by bkprecision** [comment]
Howdy! We've been on vacation for a couple of weeks and are now getting back into the swing of things. I'll take a look at it this week and get back to you.

**Comment by bkprecision** [comment]
That works as expected.

```
pi@raspberrypi ~ $ sudo python
Python 2.7.8 (default, Oct 30 2014, 18:30:15)
[GCC 4.9.1] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import visa; rm = visa.ResourceManager("@py"); inst = rm.open_resource('ASRL/dev/ttyUSB0::INSTR');
>>> inst.query("*IDN?")
u'*IDN?\r5492B Digital Multimeter,Ver1.0.12.02.09,343B12146\n'
>>>
```
