### ISSUE TITLE
More UnicodeDecodeError issues

### ISSUE THREAD

**Issue by techn0mad** [hgrecco/pyvisa-py#80]
I am having problems trying to communicate with a R&S spectrum analyzer at GPIB address 20 attached to an [ICS 9065](http://www.icselect.com/Ethernet_to_GPIB.html) Ethernet to GPIB gateway. I have observed the same kinds of problems with the release versions of PyVISA and PyVISA-Py, and in tests on both Mac OS X and Debian Linux environments. The following output is from a run under Debian Linux:
```
$ python -m visa info
Machine Details:
   Platform ID:    Linux-3.16.0-4-amd64-x86_64-with-debian-8.4
   Processor:      

Python:
   Implementation: CPython
   Executable:     /opt/anaconda-2.4.0/envs/build_spurious/bin/python
   Version:        2.7.11
   Compiler:       GCC 4.4.7 20120313 (Red Hat 4.4.7-1)
   Bits:           64bit
   Build:          Dec  6 2015 18:08:32 (#default)
   Unicode:        UCS4

PyVISA Version: 1.9.dev0

Backends:
   ni:
      Version: 1.9.dev0 (bundled with PyVISA)
      Binary library: Not found
   py:
      Version: 0.3.dev0
      ASRL INSTR:
         Please install PySerial to use this resource type.
         No module named serial
      TCPIP INSTR: Available 
      USB RAW:
         Please install PyUSB to use this resource type.
         No module named usb
      USB INSTR:
         Please install PyUSB to use this resource type.
         No module named usb
      GPIB INSTR:
         Please install linux-gpib to use this resource type.
         No module named gpib
      TCPIP SOCKET: Available 
```
Test code:
```python
import visa

class Vxi(object):
  def __init__(self):
    visa.log_to_screen()
    rm = visa.ResourceManager('@py')
    rm.open_resource('TCPIP::10.200.41.49::gpib0,20::INSTR')

if __name__ == "__main__":
  foo = Vxi()
```
Output:
```
(build_spurious)lgadalla@fvxenrf02:~$ python test.py 
2016-04-23 00:04:33,938 - pyvisa - DEBUG - SerialSession was not imported No module named serial.
2016-04-23 00:04:33,939 - pyvisa - DEBUG - USBSession and USBRawSession were not imported No module named usb.
2016-04-23 00:04:33,941 - pyvisa - DEBUG - TCPIPSession was correctly imported.
2016-04-23 00:04:33,942 - pyvisa - DEBUG - GPIBSession was not imported No module named gpib.
2016-04-23 00:04:33,942 - pyvisa - DEBUG - Created library wrapper for unset
2016-04-23 00:04:33,942 - pyvisa - DEBUG - Created ResourceManager with session 2257909
2016-04-23 00:04:33,942 - pyvisa - DEBUG - TCPIP::10.200.41.49::gpib0,20::INSTR - opening ...
2016-04-23 00:04:33,942 - pyvisa - DEBUG - RawTCPClient: connecting to socket at (10.200.41.49, 111)
2016-04-23 00:04:33,946 - pyvisa - DEBUG - Make call <PortMapperVersion.get_port: 3>, (395183, 1, 6, 0), <bound method PortMapperPacker.pack_mapping of <pyvisa-py.protocols.rpc.PortMapperPacker instance at 0x7fc06fef10e0>>, <bound method PortMapperUnpacker.unpack_uint of <pyvisa-py.protocols.rpc.PortMapperUnpacker instance at 0x7fc06fe98d88>>
Traceback (most recent call last):
  File "/opt/anaconda-2.4.0/envs/build_spurious/lib/python2.7/logging/__init__.py", line 853, in emit
    msg = self.format(record)
  File "/opt/anaconda-2.4.0/envs/build_spurious/lib/python2.7/logging/__init__.py", line 726, in format
    return fmt.format(record)
  File "/opt/anaconda-2.4.0/envs/build_spurious/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/opt/anaconda-2.4.0/envs/build_spurious/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0x86 in position 14: ordinal not in range(128)
Logged from file rpc.py, line 296
2016-04-23 00:04:34,201 - pyvisa - DEBUG - Received record through <socket._socketobject object at 0x7fc06fed8830>: '\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x15\xb3'
2016-04-23 00:04:34,201 - pyvisa - DEBUG - RawTCPClient: closing socket
2016-04-23 00:04:34,202 - pyvisa - DEBUG - RawTCPClient: connecting to socket at (10.200.41.49, 5555)
2016-04-23 00:04:34,202 - pyvisa - DEBUG - Make call 10, (1686981105L, 0, 10000, u'gpib0,20'), <bound method Vxi11Packer.pack_create_link_parms of <pyvisa-py.protocols.vxi11.Vxi11Packer instance at 0x7fc06fee8d88>>, <bound method Vxi11Unpacker.unpack_create_link_resp of <pyvisa-py.protocols.vxi11.Vxi11Unpacker instance at 0x7fc06fee8dd0>>
Traceback (most recent call last):
  File "/opt/anaconda-2.4.0/envs/build_spurious/lib/python2.7/logging/__init__.py", line 853, in emit
    msg = self.format(record)
  File "/opt/anaconda-2.4.0/envs/build_spurious/lib/python2.7/logging/__init__.py", line 726, in format
    return fmt.format(record)
  File "/opt/anaconda-2.4.0/envs/build_spurious/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/opt/anaconda-2.4.0/envs/build_spurious/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xaf in position 15: ordinal not in range(128)
Logged from file rpc.py, line 296
2016-04-23 00:04:34,458 - pyvisa - DEBUG - Received record through <socket._socketobject object at 0x7fc06fe4ec90>: '\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x07\xd4\x00\x00\x04\x00'
2016-04-23 00:04:34,458 - pyvisa - DEBUG - TCPIP::10.200.41.49::gpib0,20::INSTR - is open with session 1539275
2016-04-23 00:04:34,459 - pyvisa - DEBUG - TCPIP::10.200.41.49::gpib0,20::INSTR - closing
2016-04-23 00:04:34,459 - pyvisa - DEBUG - Make call 23, 512, <bound method Vxi11Packer.pack_device_link of <pyvisa-py.protocols.vxi11.Vxi11Packer instance at 0x7fc06fee8d88>>, <bound method Vxi11Unpacker.unpack_device_error of <pyvisa-py.protocols.vxi11.Vxi11Unpacker instance at 0x7fc06fee8dd0>>
Traceback (most recent call last):
  File "/opt/anaconda-2.4.0/envs/build_spurious/lib/python2.7/logging/__init__.py", line 853, in emit
    msg = self.format(record)
  File "/opt/anaconda-2.4.0/envs/build_spurious/lib/python2.7/logging/__init__.py", line 726, in format
    return fmt.format(record)
  File "/opt/anaconda-2.4.0/envs/build_spurious/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/opt/anaconda-2.4.0/envs/build_spurious/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xaf in position 15: ordinal not in range(128)
Logged from file rpc.py, line 296
2016-04-23 00:04:34,462 - pyvisa - DEBUG - Received record through <socket._socketobject object at 0x7fc06fe4ec90>: '\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
2016-04-23 00:04:34,462 - pyvisa - DEBUG - RawTCPClient: closing socket
2016-04-23 00:04:34,462 - pyvisa - DEBUG - TCPIP::10.200.41.49::gpib0,20::INSTR - is closed
```

**Comment by luksan** [comment]
Please see pull request #97
